services:
  - type: web
    name: garderning-laravel
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: php artisan serve --host=0.0.0.0 --port=80
